export const orders = [
    {title:'Total orders',value:48},
    {title:'Orderd items over time',value:493},
    {title:'Fulfillled orders over time',value:359},
    {title:'Delivered orders over time',value:363},
]

export const settings =['General settings','Apps','Notifications','Plan','Security']

export const orderStatus = ['All','Completed','Pending','Failed']

export const macbookData = [
  {
    model: "MacBook Air M1",
    customer_name: "John Doe",
    date: "2025-01-15",
    total_price: 999.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "",
  },
  {
    model: "MacBook Pro 14-inch",
    customer_name: "Jane Smith",
    date: "2025-01-12",
    total_price: 1999.99,
    payment_status: "Pending",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/hero/hero_endframe__e6khcva4hkeq_large.jpg",
  },
  {
    model: "MacBook Pro 16-inch",
    customer_name: "Alice Johnson",
    date: "2025-01-10",
    total_price: 2499.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/display/display__c4s5ija4qf8u_large.jpg",
  },
  {
    model: "MacBook Air M2",
    customer_name: "Bob Brown",
    date: "2025-01-09",
    total_price: 1199.99,
    payment_status: "Failed",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-air-m2/j/images/overview/hero/hero__gnfk5gngq86m_large.jpg",
  },
  {
    model: "MacBook Pro M2 Max",
    customer_name: "Charlie Davis",
    date: "2025-01-08",
    total_price: 2999.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/chip/chip__c5gvmo2pgjiy_large.jpg",
  },
  {
    model: "MacBook Air M2",
    customer_name: "Emily White",
    date: "2025-01-18",
    total_price: 2630.18,
    payment_status: "Pending",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-air-m2/j/images/overview/display/display__ebssxyd49m66_large.jpg",
  },
  {
    model: "MacBook Pro 14-inch",
    customer_name: "David Clark",
    date: "2025-01-09",
    total_price: 2224.39,
    payment_status: "Pending",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/display/display__c4s5ija4qf8u_large.jpg",
  },
  {
    model: "MacBook Pro M2 Max",
    customer_name: "Sophia Wilson",
    date: "2025-01-11",
    total_price: 1716.15,
    payment_status: "Completed",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/hero/hero_endframe__e6khcva4hkeq_large.jpg",
  },
  {
    model: "MacBook Pro 14-inch",
    customer_name: "Sophia Wilson",
    date: "2025-01-07",
    total_price: 1889.12,
    payment_status: "Failed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/display/display__c4s5ija4qf8u_large.jpg",
  },
  {
    model: "MacBook Air M2",
    customer_name: "Emily White",
    date: "2025-01-19",
    total_price: 2991.7,
    payment_status: "Failed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-air-m2/j/images/overview/display/display__ebssxyd49m66_large.jpg",
  },
  {
    model: "MacBook Pro 16-inch",
    customer_name: "Michael Scott",
    date: "2025-01-05",
    total_price: 2799.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/display/display__c4s5ija4qf8u_large.jpg",
  },
  {
    model: "MacBook Air M1",
    customer_name: "Jim Halpert",
    date: "2025-01-03",
    total_price: 1049.99,
    payment_status: "Pending",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-air-m1/i/images/overview/hero_endframe__ea0qze85eyi6_large.jpg",
  },
  {
    model: "MacBook Pro 14-inch",
    customer_name: "Pam Beesly",
    date: "2025-01-14",
    total_price: 2199.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/hero/hero_endframe__e6khcva4hkeq_large.jpg",
  },
  {
    model: "MacBook Pro M2 Max",
    customer_name: "Dwight Schrute",
    date: "2025-01-06",
    total_price: 3099.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/chip/chip__c5gvmo2pgjiy_large.jpg",
  },
  {
    model: "MacBook Air M1",
    customer_name: "Angela Martin",
    date: "2025-01-17",
    total_price: 999.99,
    payment_status: "Failed",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-air-m1/i/images/overview/hero_endframe__ea0qze85eyi6_large.jpg",
  },
  {
    model: "MacBook Air M2",
    customer_name: "Kevin Malone",
    date: "2025-01-13",
    total_price: 1399.99,
    payment_status: "Pending",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-air-m2/j/images/overview/hero/hero__gnfk5gngq86m_large.jpg",
  },
  {
    model: "MacBook Pro 16-inch",
    customer_name: "Stanley Hudson",
    date: "2025-01-16",
    total_price: 2499.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/display/display__c4s5ija4qf8u_large.jpg",
  },
  {
    model: "MacBook Pro 14-inch",
    customer_name: "Phyllis Vance",
    date: "2025-01-18",
    total_price: 2049.99,
    payment_status: "Pending",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/hero/hero_endframe__e6khcva4hkeq_large.jpg",
  },
  {
    model: "MacBook Air M2",
    customer_name: "Oscar Martinez",
    date: "2025-01-04",
    total_price: 1299.99,
    payment_status: "Completed",
    delivery_method: "Free Shipping",
    image_link: "https://www.apple.com/v/macbook-air-m2/j/images/overview/display/display__ebssxyd49m66_large.jpg",
  },
  {
    model: "MacBook Pro M2 Max",
    customer_name: "Meredith Palmer",
    date: "2025-01-11",
    total_price: 2899.99,
    payment_status: "Failed",
    delivery_method: "Amount to be Paid",
    image_link: "https://www.apple.com/v/macbook-pro-14-and-16/c/images/overview/chip/chip__c5gvmo2pgjiy_large.jpg",
  },
];

export const plans = [
  {
    id:1,
    planName:'Business',
    summary:'for slolo',
    price:19,
    plan:'Current Plan',
    features:['10 locations','24/7 chat support','Post Lite']
  },
  {
    id:2,
    planName:'Advanced',
    summary:'As your business scales',
    price:299,
    plan:'Get Started',
    features:['10 locations','24/7 chat support','Post Lite','Custom reposrts','16 additional self account']
  },
  {
    id:3,
    planName:'Plus',
    summary:'For more complex business',
    price:2999,
    plan:'Get Started',
    features:['200 locations','24/7 chat support','Post Lite','Custom reposrts','Unlimited self account','Fully automated chat with 40x capacity']
  },
]